### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by franck-paul** [JcDenis/pacKman#10]
J'ouvre un ticket pour que ça te serve d'aide-mémoire, mais je suppose que tu es déjà au courant :

    2023-02-05 08:38:41 | WARNING | …/pacKman/inc/Utils.php:231 |
    Undefined array key "name" | 88 | /plugin.php?p=pacKman
    
    2023-02-05 08:38:41 | WARNING | …/pacKman/inc/Utils.php:228 |
    Undefined array key "version" | 88 | /plugin.php?p=pacKman
    
    2023-02-05 08:38:41 | WARNING | …/pacKman/inc/Utils.php:271 |
    Undefined array key "version" | 88 | /plugin.php?p=pacKman

pacKman n'a pas trop aimé les récentes modif côté module j'ai l'impression :-)

**Comment by JcDenis** [comment]
Yep j'ai deux plugins qui se servent à la source, il faut que je les mette à jour effectivement.

**Comment by JcDenis** [comment]
Normalement auto fixé avec la prochaine nightly de Dotclear ^^

**Comment by JcDenis** [comment]
Modif poussé ce matin et donc dispo dans la 2.25-dev-r20230210
