### ISSUE TITLE
Doublons

### ISSUE THREAD

**Issue by franck-paul** [JcDenis/pacKman#12]
J'ai des modules en doublon (pas réussi à déterminer la cause) sur le 3e onglet ; c'est nouveau depuis la dernière version il me semble :

> Modification | Version | Nom | Fichier | Date
> -- | -- | -- | -- | --
> a11yConfig | 3.1.3 | a11yConfig | plugin-a11yConfig-3.1.3.zip | 23/05/2023 14:45
> adaptiveImages | 1.3 | adaptiveImages | plugin-adaptiveImages-1.3.zip | 14/05/2023 16:30
> addToAny | 1.1 | AddToAny | plugin-addToAny-1.1.zip | 18/12/2022 10:02
> antiflood | 2.1.2 | antiflood | plugin-antiflood-2.1.2.zip | 25/05/2023 11:06
> auberge | 2.0 | Auberge des blogueurs | theme-auberge-2.0.zip | 09/12/2022 18:04
> authorMode | 2.0 | authorMode | plugin-authorMode-2.0.zip | 28/11/2022 06:25
> autosave | 1.0 | Autosave | plugin-autosave-1.0.zip | 28/11/2022 06:47
> bad | 1.0 | Bad | plugin-bad-1.0.zip | 14/12/2022 08:20
> bigfoot | 1.0.2 | bigfoot | plugin-bigfoot-1.0.2.zip | 25/05/2023 06:39
> breadcrumb | 0.6.1 | Breadcrumb | plugin-breadcrumb-0.6.1.zip | 08/06/2015 20:24
> cafe-creme | 2.0 | Café Crème | theme-cafe-creme-2.0.zip | 30/11/2022 15:03
> carnaval | 2.3 | Carnaval | plugin-carnaval-2.3.zip | 16/02/2023 08:51
> catOrder | 1.1 | Ordering category entries | plugin-catOrder-1.1.zip | 18/12/2022 10:07
> checkStoreVersion | 0.1-dev | Check store version | plugin-checkStoreVersion-0.1-dev.zip | 02/12/2022 10:30
> cleanConfig | 1.4.3 | clean:config | plugin-cleanConfig-1.4.3.zip | 15/03/2016 09:41
> cleanConfig | 1.4.3 | clean:config | plugin-cleanConfig-1.4.3.zip | 15/03/2016 09:41
> cloneEntry | 3.0 | Clone Entry | plugin-cloneEntry-3.0.zip | 24/05/2023 07:53
> commentsWikibar | 3.0 | Comments Wikibar | plugin-commentsWikibar-3.0.zip | 24/05/2023 05:55
> contactMe | 3.0 | ContactMe | plugin-contactMe-3.0.zip | 25/05/2023 11:14
> cookiechoices | 1.0 | cookiechoices | plugin-cookiechoices-1.0.zip | 28/11/2022 11:44
> countdown | 1.2 | CountDown | plugin-countdown-1.2.zip | 04/07/2010 07:42
> countdown | 1.2 | CountDown | plugin-countdown-1.2.zip | 04/07/2010 07:42
> currywurst | 1.0 | Currywurst | theme-currywurst-1.0.zip | 07/12/2013 11:40
> dayMode | 2.4 | dayMode | plugin-dayMode-2.4.zip | 07/01/2023 10:53
> dc-2-13-dcLegacyPatch | 0.1 | dc-2-13-dcLegacyPatch | plugin-dc-2-13-dcLegacyPatch-0.1.zip | 14/01/2018 16:38
> dc1redirect | 1.0.2 | DC1 Redirect | plugin-dc1redirect-1.0.2.zip | 21/07/2011 15:30
> dc1redirect | 1.0.2 | DC1 Redirect | plugin-dc1redirect-1.0.2.zip | 21/07/2011 15:30
> dcRevisions | 2.0 | dcRevisions | plugin-dcRevisions-2.0.zip | 07/03/2023 09:17
> dctranslations | 1.13 | Posts Translations | plugin-dctranslations-1.13.zip | 24/07/2011 05:50
> dctranslations | 1.13 | Posts Translations | plugin-dctranslations-1.13.zip | 24/07/2011 05:50
> debug | 0.2 | debug | plugin-debug-0.2.zip | 15/05/2023 13:52
> discreteCat | 3.0.2 | Discrete category | plugin-discreteCat-3.0.2.zip | 24/05/2023 11:38
> dmHelper | 2.1 | Dashboard Module Helper Library | plugin-dmHelper-2.1.zip | 15/05/2023 17:05
> dmHostingMonitor | 2.1 | Hosting Monitor Dashboard Module | plugin-dmHostingMonitor-2.1.zip | 15/05/2023 17:03
> dmLastComments | 3.1 | Last Comments Dashboard Module | plugin-dmLastComments-3.1.zip | 13/05/2023 10:05
> dmLastSpams | 1.0 | Last Spams Dashboard Module | plugin-dmLastSpams-1.0.zip | 29/11/2022 14:51
> dmPending | 1.0 | Pending Dashboard Module | plugin-dmPending-1.0.zip | 29/11/2022 14:53
> dmPublished | 1.0 | Recently Published Posts Dashboard Module | plugin-dmPublished-1.0.zip | 29/11/2022 14:55
> dmScheduled | 1.0 | Scheduled Dashboard Module | plugin-dmScheduled-1.0.zip | 29/11/2022 14:56
> domino | 2.0 | Domino | theme-domino-2.0.zip | 30/11/2022 14:53
> doTwit | 1.3.2 | doTwit | plugin-doTwit-1.3.2.zip | 04/07/2010 07:46
> doTwit | 1.3.2 | doTwit | plugin-doTwit-1.3.2.zip | 04/07/2010 07:46
> ductileFocus | 1.0 | Ductile Focus | theme-ductileFocus-1.0.zip | 30/11/2022 15:35
> ductilePhoto | 1.0 | Ductile Photo | theme-ductilePhoto-1.0.zip | 30/11/2022 15:35
> emailNotification | 1.1 | Email notification | plugin-emailNotification-1.1.zip | 10/07/2015 06:05
> ensemble | 2.0 | Ensemble | theme-ensemble-2.0.zip | 30/11/2022 15:06
> errorlogger | 2.1.1 | ErrorLogger | plugin-errorlogger-2.1.1.zip | 22/05/2023 14:13
> externalMedia | 2.1 | External Media | plugin-externalMedia-2.1.zip | 18/12/2022 10:11
> fairEmail | 2.1 | Fair Email | plugin-fairEmail-2.1.zip | 22/05/2023 09:55
> fairTrackbacks | 1.1 | Fair Trackbacks | plugin-fairTrackbacks-1.1.zip | 01/07/2010 17:53
> fairTrackbacks | 1.1 | Fair Trackbacks | plugin-fairTrackbacks-1.1.zip | 01/07/2010 17:53
> fakemeup | 2.0 | Fake Me Up | plugin-fakemeup-2.0.zip | 26/05/2023 07:54
> fallseason | 2.0 | FallSeason | theme-fallseason-2.0.zip | 30/11/2022 15:09
> featuredMedia | 1.0 | Featured Media | plugin-featuredMedia-1.0.zip | 05/04/2023 18:03
> flocOff | 2.0 | flocOff | plugin-flocOff-2.0.zip | 29/11/2022 15:03
> GalleryInsert | 0.412 | GalleryInsert | plugin-GalleryInsert-0.412.zip | 04/12/2022 09:36
> GalleryInsert | 0.412 | GalleryInsert | plugin-GalleryInsert-0.412.zip | 04/12/2022 09:36
> googleTools | 1.0.1 | Google Tools | plugin-googleTools-1.0.1.zip | 30/11/2022 09:05
> gracefulCut | 1.0 | gracefulCut | plugin-gracefulCut-1.0.zip | 27/11/2022 06:55
> gravatar | 1.1 | Gravatar | plugin-gravatar-1.1.zip | 18/12/2022 10:13
> gris-gris | 2.0 | Gris-Gris | theme-gris-gris-2.0.zip | 30/11/2022 15:11
> growUp | 2.0 | growUp | plugin-growUp-2.0.zip | 22/05/2023 10:34
> hermine | 2.0 | Hermine | theme-hermine-2.0.zip | 30/11/2022 15:13
> highlightSearch | 1.3.2 | highlightSearch | plugin-highlightSearch-1.3.2.zip | 04/03/2013 13:10
> highlightSearch | 1.3.2 | highlightSearch | plugin-highlightSearch-1.3.2.zip | 04/03/2013 13:10
> hljs | 1.1 | Code highlight | plugin-hljs-1.1.zip | 18/12/2022 10:15
> hScroll | 2.1 | hscroll | plugin-hScroll-2.1.zip | 13/05/2023 09:13
> imgWidthAndHeightAdder | 1.0 | ImgWidthAndHeightAdder | plugin-imgWidthAndHeightAdder-1.0.zip | 11/12/2022 07:30
> integrityCheck | 3.2 | IntegrityCheck | plugin-integrityCheck-3.2.zip | 15/05/2023 17:02
> kezako | 0.9 | Kezako | plugin-kezako-0.9.zip | 09/10/2010 06:06
> kezako | 0.9 | Kezako | plugin-kezako-0.9.zip | 09/10/2010 06:06
> lazyLoading | 3.0.4 | lazyLoading | plugin-lazyLoading-3.0.4.zip | 21/05/2023 15:00
> legacyMarkdown | 3.2.1 | Markdown syntax | plugin-legacyMarkdown-3.2.1.zip | 22/05/2023 14:12
> lightbox | 2.0 | lightBox | plugin-lightbox-2.0.zip | 30/11/2022 09:22
> listImages | 3.0.1 | listImages | plugin-listImages-3.0.1.zip | 23/05/2023 14:52
> logNotices | 1.0 | Store notices in log table | plugin-logNotices-1.0.zip | 30/11/2022 10:13
> magnific-popup | 1.1 | magnific-popup | plugin-magnific-popup-1.1.zip | 01/12/2022 13:41
> maxEdit | 2.0.1 | maxEdit | plugin-maxEdit-2.0.1.zip | 23/05/2023 08:03
> mediapub | 2.0 | Media Publish | plugin-mediapub-2.0.zip | 30/11/2022 10:21
> mediaSizeClass | 1.0 | mediaSizeClass | plugin-mediaSizeClass-1.0.zip | 17/01/2023 11:27
> multipleMedia | 2.2 | multipleMedia | plugin-multipleMedia-2.2.zip | 06/12/2022 12:43
> myFavs | 3.0 | myFavs | plugin-myFavs-3.0.zip | 22/05/2023 16:30
> mymeta | 1.2.1 | My Meta | plugin-mymeta-1.2.1.zip | 22/01/2023 11:30
> navmedia | 2.0 | Media Navigator | plugin-navmedia-2.0.zip | 30/11/2022 13:36
> neodark | 2.0 | NeoDark | theme-neodark-2.0.zip | 30/11/2022 15:15
> noembedMedia | 1.1 | noembed Media | plugin-noembedMedia-1.1.zip | 18/12/2022 10:20
> notifyMe | 2.2.3 | Browser notifications | plugin-notifyMe-2.2.3.zip | 22/05/2023 14:11
> offline | 0.5 | Offline mode | plugin-offline-0.5.zip | 04/07/2010 08:26
> offline | 0.5 | Offline mode | plugin-offline-0.5.zip | 04/07/2010 08:26
> open-time | 2.0 | Open-Time | theme-open-time-2.0.zip | 30/11/2022 15:17
> packager | 0.2-beta1 | Packager | plugin-packager-0.2-beta1.zip | 01/07/2010 18:53
> packager | 0.2-beta1 | Packager | plugin-packager-0.2-beta1.zip | 01/07/2010 18:53
> pacKman | 2021.03.04 | pacKman | plugin-pacKman-2021.03.04.zip | 04/03/2021 10:42
> pingMastodon | 2.0 | pingMastodon | plugin-pingMastodon-2.0.zip | 18/05/2023 13:12
> piwik | 0.8.1 | Piwik | plugin-piwik-0.8.1.zip | 19/07/2010 19:46
> piwik | 0.8.1 | Piwik | plugin-piwik-0.8.1.zip | 19/07/2010 19:46
> postTitleAutonum | 2.3.1 | postTitleAutonum | plugin-postTitleAutonum-2.3.1.zip | 22/05/2023 14:10
> private | 2.1.1 | PrivateMode | plugin-private-2.1.1.zip | 03/02/2023 15:55
> related | 1.1-RC1 | Related Pages | plugin-related-1.1-RC1.zip | 01/07/2010 22:08
> related | 1.1-RC1 | Related Pages | plugin-related-1.1-RC1.zip | 01/07/2010 22:08
> retrocontrol | 4.1.1 | Rétrocontrôle | plugin-retrocontrol-4.1.1.zip | 22/05/2023 14:09
> rosetta | 1.1 | Rosetta | plugin-rosetta-1.1.zip | 18/12/2022 10:24
> series | 2.1 | Series | plugin-series-2.1.zip | 18/12/2022 10:25
> signal | 2.0 | Signal | plugin-signal-2.0.zip | 23/05/2023 09:38
> sitemaps | 3.0.2 | Sitemaps | plugin-sitemaps-3.0.2.zip | 21/05/2023 15:11
> smile | 2.0 | Smile | theme-smile-2.0.zip | 30/11/2022 15:19
> smiliesEditor | 1.3.1 | smiliesEditor | plugin-smiliesEditor-1.3.1.zip | 16/02/2023 08:49
> snapme | 0.8 | SnapMe | plugin-snapme-0.8.zip | 04/07/2010 08:19
> snapme | 0.8 | SnapMe | plugin-snapme-0.8.zip | 04/07/2010 08:19
> socialMeta | 3.0 | socialMeta | plugin-socialMeta-3.0.zip | 26/05/2023 12:48
> socialShare | 2.1 | socialShare | plugin-socialShare-2.1.zip | 18/12/2022 10:31
> spamHelper | 0.1 | spamHelper | plugin-spamHelper-0.1.zip | 22/11/2018 16:04
> spamplemousse2 | 4.1.4 | Spamplemousse2 | plugin-spamplemousse2-4.1.4.zip | 25/05/2023 20:00
> stacker | 0.5 | Stacker | plugin-stacker-0.5.zip | 09/10/2010 06:06
> stacker | 0.5 | Stacker | plugin-stacker-0.5.zip | 09/10/2010 06:06
> standblog | 1.7 | Standblog | theme-standblog-1.7.zip | 22/01/2022 09:14
> staticCache | 2.3.1 | Static Cache | plugin-staticCache-2.3.1.zip | 19/05/2023 05:24
> stopForumSpam | 2.1 | Stop Forum Spam | plugin-stopForumSpam-2.1.zip | 22/05/2023 09:56
> supin | 2.0 | Supin | theme-supin-2.0.zip | 30/11/2022 14:56
> sysInfo | 4.5.1 | sysInfo | plugin-sysInfo-4.5.1.zip | 22/05/2023 14:07
> tidyAdmin | 4.2.1 | Tidy Administration | plugin-tidyAdmin-4.2.1.zip | 22/05/2023 14:06
> translatedwidgets | 1.7 | Widgets | plugin-translatedwidgets-1.7.zip | 09/10/2010 06:06
> translatedwidgets | 1.7 | Widgets | plugin-translatedwidgets-1.7.zip | 09/10/2010 06:06
> tribe | 2.0 | tribe | theme-tribe-2.0.zip | 30/11/2022 15:21
> tweakurls | 4.2 | tweakURLs | plugin-tweakurls-4.2.zip | 15/05/2023 15:14
> twentytwenty | 1.0 | TwentyTwenty | plugin-twentytwenty-1.0.zip | 30/11/2022 14:33
> twitterPost | 1.4 | TwitterPost | plugin-twitterPost-1.4.zip | 04/07/2010 08:14
> twitterPost | 1.4 | TwitterPost | plugin-twitterPost-1.4.zip | 04/07/2010 08:14
> typo | 3.2 | Typo | plugin-typo-3.2.zip | 13/05/2023 15:08
> userThumbSizes | 2.4.1 | User defined thumbnails | plugin-userThumbSizes-2.4.1.zip | 18/05/2023 15:12
> utf8mb4 | 2.2 | utf8mb4 | plugin-utf8mb4-2.2.zip | 13/05/2023 14:49
> wideEdit | 1.0 | wideEdit | plugin-wideEdit-1.0.zip | 30/11/2022 14:41
> wordCount | 3.3.4 | Word Count | plugin-wordCount-3.3.4.zip | 22/05/2023 14:02
> writers | 2.0 | Writers | plugin-writers-2.0.zip | 30/11/2022 14:46
> yash | 2.1 | YASH | plugin-yash-2.1.zip | 18/12/2022 10:34
> zenEdit | 3.3.1 | zenEdit | plugin-zenEdit-3.3.1.zip | 22/05/2023 14:04
> zh2 | 2.0 | zh2 | theme-zh2-2.0.zip | 30/11/2022 15:24
> zh2-auto | 2.0 | zh2-auto | theme-zh2-auto-2.0.zip | 30/11/2022 15:27
> zh2-dark | 2.0 | zh2-dark | theme-zh2-dark-2.0.zip | 30/11/2022 15:29
> zh2-dark | 2.0 | zh2-dark | theme-zh2-dark-2.0.zip | 30/11/2022 15:29

**Comment by JcDenis** [comment]
Tu n'y enregistrerais pas dans deux répertoires par hasard ?

**Comment by franck-paul** [comment]
Nope, un seul est défini dans la config de pacKman

**Comment by franck-paul** [comment]
Et le truc bizarre c'est que pas seulement des thèmes qui sont en double (en particulier, le dernier de la liste, zh2-dark, est vu comme un plugin et comme un thème dans getPackages() :-/

Par ailleurs j'ai une archive d'un plugin qui n'existe pas dans ma config actuelle (donc uniquement le zip dans le répertoire de dépôt) et il est en double aussi (twitterPost).

**Comment by franck-paul** [comment]
Doit y avoir un problème de détermination du type de module, plugin ou thème, qui fait qu'il est considéré comme étant les deux types, mais c'est pas systématique.

**Comment by JcDenis** [comment]
Je ferme pour le moment. Si vraiment ça gène on rouvre et j'_essaierai_ de faire quelque chose…
