### ISSUE TITLE
Suggestion de présentation

### ISSUE THREAD

**Issue by Philippe-dev** [JcDenis/pacKman#6]
La page de configuration du plugin pourrait-elle être sur la même page que les autres options ? Par exemple simplement dans un onglet supplémentaire ? Je trouve qu'aller chercher le petit lien en bas de page n'est pas le plus pratique

Mais il y a peut-être une raison pour faire comme ça. En tout cas c'est un chouette plugin qui marche du tonnerre ;)

**Comment by JcDenis** [comment]
J'utilise le plus souvent le systéme dédié à ça dans dotclear, c'est à dire le _config.php et ses avantages. De plus généralement dans mes plugins on n'a pas accès enfin je n'affiche pas les liens vers la page du plugin tant qu'on ne la pas activé dans la config.
Je vais y réfléchir mais pas certains du tout de changer ça.

**Comment by Philippe-dev** [comment]
C'est toi le patron, ça ne change rien à l'efficacité du plugin :)

**Comment by franck-paul** [comment]
> La page de configuration du plugin pourrait-elle être sur la même page que les autres options ? Par exemple simplement dans un onglet supplémentaire ? Je trouve qu'aller chercher le petit lien en bas de page n'est pas le plus pratique
> 
> Mais il y a peut-être une raison pour faire comme ça. En tout cas c'est un chouette plugin qui marche du tonnerre ;)

Installe la dernière version du plugin tidyAdmin (3.1) et coche la case "Remonter le lien vers les réglages de plugin en haut de la page" sur le 1er onglet ("Options"), pour voir ;-)

**Comment by Philippe-dev** [comment]
Oui, c'est un peu mieux. Je parlais toutefois d'intégrer la configuration dans la page d'admin du plugin avec un nouvel onglet, mais c'est pas bien grave, juste une affaire de goût et d'ergonomie ;)

**Comment by franck-paul** [comment]
> Après avoir revu et corrigé un paquet de plugins, je confirme que je ne me dirige pas vers l'intégration des options de config des plugins dans leur page principale. Sauf cas spéciaux.

Dans un onglet spécifique si besoin ?

**Comment by franck-paul** [comment]
![](https://user-images.githubusercontent.com/307049/234548269-d6430146-6577-4873-80d8-2e79cc104781.jpg)

**Comment by JcDenis** [comment]
Mais toute la gestion derrière est dans le Config. C'est tellement plus simple et lisible côté code de séparer les deux.

**Comment by JcDenis** [comment]
Mais toute la gestion derrière est dans le Config. C'est tellement plus simple et lisible côté code de séparer les deux.
