### ISSUE TITLE
Fatal error après mise à jour avec la dernière version

### ISSUE THREAD

**Issue by franck-paul** [JcDenis/pacKman#9]
```
Fatal error: Uncaught Error: Class "Dotclear\Plugin\pacKman\Admin" not found in /Users/franck/Documents/EGO/Geekeries/Internet/htdocs/git-plugins/pacKman/_admin.php:16

Stack trace:

#0 /Users/franck/Documents/EGO/Geekeries/Internet/htdocs/git-dc/inc/core/class.dc.modules.php(1151): require()
#1 /Users/franck/Documents/EGO/Geekeries/Internet/htdocs/git-dc/inc/core/class.dc.modules.php(1102): dcModules->loadModuleFile('/Users/franck...')
#2 /Users/franck/Documents/EGO/Geekeries/Internet/htdocs/git-dc/inc/core/class.dc.modules.php(459): dcModules->loadNsFile('pacKman', 'admin')
#3 /Users/franck/Documents/EGO/Geekeries/Internet/htdocs/git-dc/inc/admin/class.dc.admin.php(207): dcModules->loadModules('/Users/franck...', 'admin', 'fr')
#4 /Users/franck/Documents/EGO/Geekeries/Internet/htdocs/git-dc/inc/admin/prepend.php(23): dcAdmin->init()
#5 /Users/franck/Documents/EGO/Geekeries/Internet/htdocs/git-dc/admin/plugins.php(9): require('/Users/franck...')
#6 {main} thrown in /Users/franck/Documents/EGO/Geekeries/Internet/htdocs/git-plugins/pacKman/_admin.php on line 16
```

Config de développement :
- deux chemins de plugins dans DC_PLUGINS_ROOT, celui de Dotclear et un autre situé à l'extérieur.
- PHP 8.1 et MySQL
- pacKman installé dans le 2e répertoire, en dehors de Dotclear

Peut-être lié aux deux répertoires de plugins ? Je n'ai pas approfondi.

**Comment by JcDenis** [comment]
J'utilise 3 répertoires de plugins (testé dans les 3) et je n'arrive pas à reproduire (dc dev / php 8.1.12 / windows) :(

Possibilités :
- espace de noms dans les implode() des _perpend.php et Prepend.php,
- test de constante dans les defined() sur l'espace de nom root,

Peux tu essayer en virant le test class_exists() du fichier _prepend.php ?

**Comment by franck-paul** [comment]
Trouvé :

C'est `implode('\\', ['Dotclear','Plugin', basename(__NAMESPACE__), $lib])` qui pose problème, chez moi ça retourne `Dotclear\Plugin\Dotclear\Plugin\pacKman\Admin`

Sachant que `basename(__NAMESPACE__)` donne `Dotclear\Plugin\pacKman`.

Le code modifié qui fonctionne chez moi :

```php
        foreach (self::LIBS as $lib) {
            Clearbricks::lib()->autoload([
                implode('\\', [basename(__NAMESPACE__), $lib]) => __DIR__ . DIRECTORY_SEPARATOR . $lib . '.php',
            ]);
        }
```

Du coup je ne comprends pas pourquoi ça fonctionne chez toi !

**Comment by JcDenis** [comment]
basename(__NAMESPACE__) retourne paKman chez moi, et c'est bien une différence de system windows vs linux, basename() sous windows accepte les séparateurs \ pas sous Linux ... Faut que je trouve autre chose pour le faire
